disable /proc/xen mount if xentools service start script

diff --git a/stemcell_builder/stages/system_ubuntu_xen_tools/assets/xe-linux-distribution b/stemcell_builder/stages/system_ubuntu_xen_tools/assets/xe-linux-distribution
--- a/stemcell_builder/stages/system_ubuntu_xen_tools/assets/xe-linux-distribution
+++ b/stemcell_builder/stages/system_ubuntu_xen_tools/assets/xe-linux-distribution
@@ -49,22 +49,24 @@ fi
 
 start()
 {
-    if [ ! -e /proc/xen/xenbus ] ; then
-	if [ ! -d /proc/xen ] ; then
-	    action $"Mounting xenfs on /proc/xen:" /bin/false
-	    echo "Could not find /proc/xen directory."
-	    echo "You need a post 2.6.29-rc1 kernel with CONFIG_XEN_COMPAT_XENFS=y and CONFIG_XENFS=y|m"
-	    exit 1
-	else 
-	    # This is needed post 2.6.29-rc1 when /proc/xen support was pushed upstream as a xen filesystem
-	    action $"Mounting xenfs on /proc/xen:" mount -t xenfs none /proc/xen
-	fi
-    fi
+# DISABLE /proc/xen mount (incompatibilites with garden containers)
+#
+#    if [ ! -e /proc/xen/xenbus ] ; then
+#	if [ ! -d /proc/xen ] ; then
+#	    action $"Mounting xenfs on /proc/xen:" /bin/false
+#	    echo "Could not find /proc/xen directory."
+#	    echo "You need a post 2.6.29-rc1 kernel with CONFIG_XEN_COMPAT_XENFS=y and CONFIG_XENFS=y|m"
+#	    exit 1
+#	else 
+#	    # This is needed post 2.6.29-rc1 when /proc/xen support was pushed upstream as a xen filesystem
+#	    action $"Mounting xenfs on /proc/xen:" mount -t xenfs none /proc/xen
+#	fi
+#   fi
 
-    if [ -e /proc/xen/capabilities ] && grep -q control_d /proc/xen/capabilities ; then
-	# Do not want daemon in domain 0
-	exit 0
-    fi
+#    if [ -e /proc/xen/capabilities ] && grep -q control_d /proc/xen/capabilities ; then
+#	# Do not want daemon in domain 0
+#	exit 0
+#   fi
 
     action $"Detecting Linux distribution version:" \
 	${XE_LINUX_DISTRIBUTION} ${XE_LINUX_DISTRIBUTION_CACHE}
